CREATE DATABASE ChatDB;

USE ChatDB;

CREATE TABLE Users
(
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) UNIQUE NOT NULL,
    Password VARCHAR(50) NOT NULL
);

CREATE TABLE Messages
(
    MessageID INT AUTO_INCREMENT PRIMARY KEY,
    Sender VARCHAR(50),
    Message TEXT,
    MessageTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);